### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by MCerk** [sibiraj-s/merge-json-webpack-plugin#2]
Throws error `TypeError: Cannot destructure property 'RawSource' of 'sources' as it is undefined.` when using it like this:

```js
new MergeJsonPlugin({
  force: false,
  group: [
    {
      files: "*.json",
      to: "out.json",
      mergeFn: (prev, current) => prev.concat(current),
    },
  ],
});
```

Json files are all arrays of objects.

**Comment by sibiraj-s** [comment]
Hi. You must be using webpack 5 for versions >3. If yes can you try reinstalling the packages (delete `node_modules` and reinstall).

Also update the options.

```js
new MergeJsonPlugin({
  force: false,
  group: [
    {
      files: "*.json",
      to: "out.json",
    },
 ],
  mergeFn: (prev, current) => prev.concat(current)
}),
```

Aslo, I just found a bug with the merging arrays. I will be fixing it today.

**Comment by sibiraj-s** [comment]
I have fixed the issue with array concat in `v5.0.1`.

**Comment by oyemeLife** [comment]
Same for me it fails when I include that line 

`const MergeJsonPlugin = require('merge-json-webpack-plugin')`
I deleted node_modules folder and I'm using v5.0.1 version

**Comment by sibiraj-s** [comment]
can you put a simple repo to reproduce this? I will look into this asap.

**Comment by sibiraj-s** [comment]
there was an issue with glob ignore pattern. I fixed it now. in v5.0.2. 
If the error is `Cannot destructure property 'RawSource' of 'sources' as it is undefined`, you need Webpack 5 and node ~14~ >10.13. Reopen if the issue still persists.
