### ISSUE TITLE
Feature request: allow individual files to be transformed

### ISSUE THREAD

**Issue by solowt** [sibiraj-s/merge-json-webpack-plugin#8]
We have the need to transform individual files so that a file named `test.json` with the content `{ a: 5, b: 6 }` is merged as `{ test: { a: 5, b: 6 } }`.

A simple way to enable this would be to include a `transformFile` option so that each file can be transformed by a user-passed function.

Implementation would look something like https://github.com/sibiraj-s/merge-json-webpack-plugin/compare/master...solowt:merge-json-webpack-plugin:add-transform-file

**Comment by sibiraj-s** [comment]
Added in v6.2.0
